In [0]:
# Install the PyDrive wrapper & import libraries.
# This only needs to be done once per notebook.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [4]:
from pydrive.drive import GoogleDrive

#drive = GoogleDrive(gauth) # Create GoogleDrive instance with authenticated GoogleAuth instance

# Auto-iterate through all files in the root folder.
file_list = drive.ListFile({'q': "'root' in parents and trashed=false"}).GetList()
for file1 in file_list:
  print('title: %s, id: %s' % (file1['title'], file1['id']))

title: data with time aggregates only imp.csv, id: 173Pd3wmYlTs9C7JJS9f0uXYi5GgD-MZ9
title: data with time aggregates.csv, id: 1fxLXWKLqnvxX20rOdE3SMKWp7ct7Bjkw
title: adatastd.csv, id: 11wVyGnnsgmUpjneqeLn0YZYYwrynASzy
title: adata.csv, id: 1a6S3r-bVBu7tDOnWXgUWt6W_YC0INhfs
title: test.csv, id: 1PjS8wfB5dR3CbO7ZVsiamaJ5QXcTd0tr
title: TransactionData_Train.csv, id: 1Xk0ajTMzg8yCaVOaZ2fux1EbSVtzXnMC
title: TransactionData_Train.csv, id: 1HJPmBGbWTZEGrky71AP8RyEpzLeo4PTY
title: TransactionData_Test.csv, id: 1PizRWYEmuAXoi7pLY7gXKOtxiIYFk0Bf
title: AggregateData_Train.csv, id: 14XJUlRvv3prdTzlffMjpsNAzJGszmufL
title: AggregateData_Test.csv, id: 1lcPedqVO8yO3gYpLovSEM0jS9Zr3BYYe
title: train_data, id: 14pl-b0ZlUJGfaBDYdiA9aw7wQ0_vEE_3
title: mask_rcnn_pneumonia_2.h5, id: 1ddek9RQCPVOnP2yX85LKe7G6TbLJcA7K
title: mask_rcnn_pneumonia_1.h5, id: 1wpKc4qkyfQSMGizFTnW58ZETTVfxsGQO
title: events.out.tfevents.1537702634.f9d6d36cbe00, id: 1K4EhwyZ1_27se18lDshsVIOjhdFbaX3h
title: kaggle.json, id: 1A

In [0]:
file_id = '1Xk0ajTMzg8yCaVOaZ2fux1EbSVtzXnMC'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('TransactionData_Train.csv')

file_id = '1PizRWYEmuAXoi7pLY7gXKOtxiIYFk0Bf'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('TransactionData_Test.csv')

file_id = '14XJUlRvv3prdTzlffMjpsNAzJGszmufL'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('AggregateData_Train.csv')

file_id = '1lcPedqVO8yO3gYpLovSEM0jS9Zr3BYYe'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('AggregateData_Test.csv')

In [0]:
file_id = '1PjS8wfB5dR3CbO7ZVsiamaJ5QXcTd0tr'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('test.csv')

file_id = '1a6S3r-bVBu7tDOnWXgUWt6W_YC0INhfs'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('adata.csv')

In [0]:
file_id = '11wVyGnnsgmUpjneqeLn0YZYYwrynASzy'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('adatastd.csv')

In [0]:
file_id = '173Pd3wmYlTs9C7JJS9f0uXYi5GgD-MZ9'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('data.csv')

In [0]:
! pip install -U setuptools

    100% |████████████████████████████████| 573kB 6.1MB/s 
  Found existing installation: setuptools 40.5.0
    Uninstalling setuptools-40.5.0:
      Successfully uninstalled setuptools-40.5.0


In [0]:
!pip install cython

    100% |████████████████████████████████| 2.1MB 5.8MB/s 


In [9]:
!pip install lightgbm

    100% |████████████████████████████████| 1.2MB 8.0MB/s 


In [10]:
!pip install git+https://github.com/h2oai/pystacknet.git

  Cloning https://github.com/h2oai/pystacknet.git to /tmp/pip-req-build-fc526gb8
  Running setup.py bdist_wheel for pystacknet ... - \ done
  Stored in directory: /tmp/pip-ephem-wheel-cache-8a031tzz/wheels/07/db/f3/442fb38c907f06e5341b941023ee3d8e23aeea305ac4243ed3
Successfully built pystacknet


In [11]:
!pip install git+https://github.com/ibayer/fastFM.git

  Cloning https://github.com/ibayer/fastFM.git to /tmp/pip-req-build-e5dksp_1
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-e5dksp_1/setup.py", line 3, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-e5dksp_1/


In [0]:
!pip install vowpalwabbit

  Using cached https://files.pythonhosted.org/packages/56/45/278a8427aa859888b3fb3e3debeea086557df8def22a23561bfe45e1fb03/vowpalwabbit-8.5.0.tar.gz
  Running setup.py bdist_wheel for vowpalwabbit ... - \ error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3q7u70t4/vowpalwabbit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-por6jods --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/sklearn_vw.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/__init__.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/pyvw.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
  running egg_info
  writing vowpalwabbit.egg-info/PKG-INFO
  

In [0]:
!pip install libsasl2-dev

  Could not find a version that satisfies the requirement libsasl2-dev (from versions: )
No matching distribution found for libsasl2-dev


In [12]:
!pip install rgf_python

    100% |████████████████████████████████| 757kB 7.1MB/s 


In [0]:
import pandas as pd
import numpy as np
#import xgboost as xgb
import lightgbm as lgb


In [0]:
from pandas import compat

compat.PY3 = True

In [0]:
#adata=pd.read_csv('AggregateData_Train.csv')
tdata=pd.read_csv('TransactionData_Train.csv')
testtdata=pd.read_csv('TransactionData_Test.csv')
#test=pd.read_csv('AggregateData_Test.csv')

adata=pd.read_csv('adata.csv')
test=pd.read_csv('test.csv')
adatastd=pd.read_csv('adatastd.csv')
data=pd.read_csv('data.csv')

In [0]:
trans=tdata.append(testtdata)
trans.head

In [0]:
del adatastd['V2']

In [0]:
adatastd.head

<bound method NDFrame.head of              V2        V3        V4         V5        V6        V7        V8  \
0     -1.203109 -0.610826 -1.220129  -0.148228 -0.198856 -0.241686 -0.031532   
1     -0.216012 -0.668120  1.234250  -0.148228 -0.198856 -0.241686 -0.031532   
2      1.032628  2.405618  1.814261  -0.148228 -0.198856  0.795731 -0.031532   
3      1.489120 -0.668120  0.705438  -0.084060 -0.198856 -0.241686 -0.031532   
4     -0.112496 -0.526932  0.998979  -0.148228 -0.198856 -0.241686 -0.031532   
5      0.687708  1.867126 -0.289528  -0.148228 -0.198856 -0.241686 -0.031532   
6     -1.505871  1.653980 -1.058487  -0.148228 -0.198856 -0.241686 -0.031532   
7     -1.409471 -0.668120  0.507225   5.193733 -0.198856 -0.241686 -0.031532   
8     -0.908806 -0.668120  1.689433  -0.148228 -0.198856 -0.241686 -0.031532   
9      0.569155 -0.668120 -1.220129  -0.148228 -0.198856 -0.241686 -0.031532   
10     0.888296  0.437171  1.182807  -0.148228 -0.198856 -0.241686 -0.031532   
11    -1.5

In [0]:
y_train=adata['bad_flag']
#adata.drop(columns=['bad_flag', 'UID','V2'],axis=1,inplace=True)
#adata=adata.replace('?',np.NaN)


In [0]:
#adata=adata.astype(dtype='float',error='ignore')


In [0]:
#dtrain=xgb.DMatrix(adata,y_train)

In [0]:
#model=xgb.XGBClassifier(n_estimators=3000,objective= 'binary:logitraw')

In [0]:
#trained=model.fit(adata,y_train)

In [0]:
#eval_set  = [(adata,y_train)]
#tra=model.fit(adata, y_train, eval_set=eval_set,
#        eval_metric="auc")

In [0]:
list(adata)

['UID',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'V29',
 'V30',
 'V31',
 'V32',
 'V33',
 'V34',
 'V35',
 'V36',
 'V37',
 'V38',
 'V39',
 'V40',
 'V41',
 'V42',
 'V43',
 'V44',
 'V45',
 'V46',
 'V47',
 'V48',
 'V49',
 'V50',
 'V51',
 'V52',
 'V53',
 'bad_flag',
 'AFM',
 'AFT',
 'AID',
 'ALC',
 'APC',
 'APD',
 'AQD',
 'ARC',
 'ASD',
 'ATC',
 'ATD',
 'ATW',
 'BCS',
 'BFT',
 'BHT',
 'BPC',
 'BRD',
 'CAC',
 'CAD',
 'CBA',
 'CBC',
 'CBD',
 'CCC',
 'CCD',
 'CCP',
 'CCR',
 'CDC',
 'CDD',
 'CFC',
 'CGL',
 'CHD',
 'CHG',
 'CHI',
 'CHO',
 'CHQ',
 'CHR',
 'CHS',
 'CIC',
 'CIN',
 'CLC',
 'CLD',
 'CLS',
 'CMC',
 'CMD',
 'COC',
 'CPC',
 'CRC',
 'CSA',
 'CSC',
 'CSD',
 'CST',
 'CSW',
 'CTC',
 'CTD',
 'CTF',
 'CVC',
 'CVD',
 'DBC',
 'DBD',
 'DCC',
 'DCD',
 'DDD',
 'DDI',
 'DDS',
 'DFC',
 'DFD',
 'DIC',
 'DIN',
 'DRC',
 'DRD',
 'DTC',
 'D

In [0]:
uid=test['UID']
#test.drop(columns=['UID','V2'],axis=1,inplace=True)
#test=test.replace('?',np.NaN)
#test=test.astype(dtype='float',error='ignore')

In [0]:
#pred=tra.predict(test)

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [0]:
train=lgb.Dataset(data=adatastd[0:20000],label=y_train[0:20000])
valid=lgb.Dataset(data=adatastd[20000:26775],label=y_train[20000:26775])

In [0]:
train=lgb.Dataset(data=data[0:20000],label=y_train[0:20000])
valid=lgb.Dataset(data=data[20000:26775],label=y_train[20000:26775])

In [0]:
parameters = {
    'application': 'binary',
    'objective': 'binary',
    'metric': 'auc',
    'is_unbalance': 'true',
    'boosting': 'gbdt',
    'num_leaves': 31,
    'feature_fraction': 0.5,
    'bagging_fraction': 0.5,
    'bagging_freq': 20,
    'learning_rate': 0.05,
    'verbose': 0
}

In [0]:
model = lgb.train(parameters,
                       train,
                       valid_sets=[train,valid],
                       num_boost_round=5000)

[1]	training's auc: 0.623915	valid_1's auc: 0.558093
[2]	training's auc: 0.677806	valid_1's auc: 0.586122
[3]	training's auc: 0.704946	valid_1's auc: 0.60296
[4]	training's auc: 0.725335	valid_1's auc: 0.614345
[5]	training's auc: 0.733038	valid_1's auc: 0.621664
[6]	training's auc: 0.738783	valid_1's auc: 0.62331
[7]	training's auc: 0.74761	valid_1's auc: 0.626386
[8]	training's auc: 0.752065	valid_1's auc: 0.627011
[9]	training's auc: 0.757447	valid_1's auc: 0.628136
[10]	training's auc: 0.761974	valid_1's auc: 0.632836
[11]	training's auc: 0.765299	valid_1's auc: 0.634586
[12]	training's auc: 0.767444	valid_1's auc: 0.635958
[13]	training's auc: 0.770497	valid_1's auc: 0.637545
[14]	training's auc: 0.772457	valid_1's auc: 0.639622
[15]	training's auc: 0.775032	valid_1's auc: 0.640919
[16]	training's auc: 0.778013	valid_1's auc: 0.643916
[17]	training's auc: 0.779758	valid_1's auc: 0.645977
[18]	training's auc: 0.781242	valid_1's auc: 0.64637
[19]	training's auc: 0.781787	valid_1's a

[5000]	training's auc: 0.999989	valid_1's auc: 0.636327

In [0]:
cv=lgb.cv(parameters,train,num_boost_round=200,verbose_eval=1,early_stopping_rounds=5,nfold=5)

[1]	cv_agg's auc: 0.565668 + 0.0120267
[2]	cv_agg's auc: 0.588155 + 0.0132221
[3]	cv_agg's auc: 0.594443 + 0.0128957
[4]	cv_agg's auc: 0.607858 + 0.0142731
[5]	cv_agg's auc: 0.613917 + 0.0147285
[6]	cv_agg's auc: 0.616441 + 0.0157221
[7]	cv_agg's auc: 0.621808 + 0.017613
[8]	cv_agg's auc: 0.62425 + 0.0166857
[9]	cv_agg's auc: 0.626623 + 0.0170289
[10]	cv_agg's auc: 0.629759 + 0.0180846
[11]	cv_agg's auc: 0.630502 + 0.0184073
[12]	cv_agg's auc: 0.632068 + 0.0188775
[13]	cv_agg's auc: 0.63321 + 0.0181469
[14]	cv_agg's auc: 0.633998 + 0.0178601
[15]	cv_agg's auc: 0.634797 + 0.0176579
[16]	cv_agg's auc: 0.635613 + 0.0177236
[17]	cv_agg's auc: 0.636436 + 0.0173956
[18]	cv_agg's auc: 0.63734 + 0.0178838
[19]	cv_agg's auc: 0.639066 + 0.0178574
[20]	cv_agg's auc: 0.639831 + 0.0185035
[21]	cv_agg's auc: 0.640701 + 0.0191918
[22]	cv_agg's auc: 0.642419 + 0.0189208
[23]	cv_agg's auc: 0.643122 + 0.0190667
[24]	cv_agg's auc: 0.645095 + 0.019428
[25]	cv_agg's auc: 0.64566 + 0.0201983
[26]	cv_agg's a

cv_agg's auc: 0.652026 + 0.0163164

In [0]:
#stacknet
from pystacknet.pystacknet import StackNetClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, ExtraTreesClassifier, ExtraTreesRegressor, GradientBoostingClassifier,GradientBoostingRegressor
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.decomposition import PCA,FactorAnalysis,FastICA
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn import neighbors
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
#from vowpalwabbit.sklearn_vw import VWClassifier
from rgf.sklearn import RGFClassifier
#from fastFM import sgd

models=[ \
            
            [RandomForestClassifier (n_estimators=300, criterion="entropy", max_depth=5, max_features=0.5, random_state=1),\
             ExtraTreesClassifier (n_estimators=300, max_depth=5, max_features=0.5, random_state=1),\
             GradientBoostingClassifier(n_estimators=300, learning_rate=0.1, max_depth=5, max_features=0.5, random_state=1),\
             LogisticRegression(random_state=1),\
             PCA(n_components=20,random_state=1),\
             FactorAnalysis(n_components=20,random_state=1),\
             FastICA(n_components=20,random_state=1),
             LogisticRegression(C=1,  random_state=1),
             LogisticRegression(C=3,  random_state=1),
             Ridge(alpha=0.1, random_state=1),
             LogisticRegression(penalty="l1", C=1, random_state=1),
             XGBClassifier(max_depth=5,learning_rate=0.1, n_estimators=300, objective="binary:logistic", n_jobs=1, booster="gbtree", random_state=1, colsample_bytree=0.4 ),
             XGBClassifier(max_depth=5,learning_rate=0.1, n_estimators=1000, objective="binary:logistic", n_jobs=1, booster="gbtree", random_state=1, colsample_bytree=0.4 ),
             XGBClassifier(max_depth=5,learning_rate=0.3, reg_lambda=0.1, n_estimators=300, objective="binary:logistic", n_jobs=1, booster="gblinear", random_state=1, colsample_bytree=0.4 ),
             XGBClassifier(max_depth=5,learning_rate=0.1, n_estimators=300, objective="rank:pairwise", n_jobs=1, booster="gbtree", random_state=1, colsample_bytree=0.4 ),
             LGBMClassifier(boosting_type='gbdt', num_leaves=40, max_depth=-1, learning_rate=0.01, n_estimators=1000, subsample_for_bin=1000, objective="xentropy", min_split_gain=0.0, min_child_weight=0.01, min_child_samples=10, subsample=0.9, subsample_freq=1, colsample_bytree=0.5, reg_alpha=0.0, reg_lambda=0.0, random_state=1, n_jobs=1), 
             LGBMClassifier(boosting_type='dart', num_leaves=40, max_depth=-1, learning_rate=0.1, n_estimators=1000, subsample_for_bin=1000, objective="xentropy", min_split_gain=0.0, min_child_weight=0.01, min_child_samples=10, subsample=0.9, subsample_freq=1, colsample_bytree=0.5, reg_alpha=0.0, reg_lambda=0.0, random_state=1, n_jobs=1), 
             #KNeighborsClassifier(n_neighbors=5),
             MLPClassifier(solver='adam', alpha=1e-3,hidden_layer_sizes=(5, 2), random_state=1),\
             #VWClassifier(),\
             RGFClassifier(max_leaf=100,algorithm="RGF",test_interval=25),\
             #sgd.FMClassification(n_iter=1000, init_stdev=0.1, l2_reg_w=0,l2_reg_V=0, rank=2, step_size=0.1)
            ],\
            
            [RandomForestClassifier (n_estimators=200, criterion="entropy", max_depth=5, max_features=0.5, random_state=1),\
             #MLPClassifier(solver='adam', alpha=1e-3,hidden_layer_sizes=(5, 2), random_state=1),\
             LogisticRegression(C=2,  random_state=1),\
             XGBClassifier(max_depth=5,learning_rate=0.1, n_estimators=1000, objective="binary:logistic", n_jobs=1, booster="gbtree", random_state=1, colsample_bytree=0.4 )
            ],\
            [LogisticRegression(C=2,  random_state=1)]
            
            
            ]
model=StackNetClassifier(models, metric="auc", folds=4,restacking=True,use_retraining=True, use_proba=True,random_state=12345,n_jobs=1, verbose=1)

In [0]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
data = imp.fit_transform(data)

In [27]:
mod=model.fit(data[0:26775],y_train)

====================== Start of Level 0 ======================
Input Dimensionality 300 at Level 0 
19 models included in Level 0 
Fold 1/4 , model 0 , auc===0.667256 
Fold 1/4 , model 1 , auc===0.653932 
Fold 1/4 , model 2 , auc===0.652139 
Fold 1/4 , model 3 , auc===0.633489 
Fold 1/4 , model 7 , auc===0.633489 
Fold 1/4 , model 8 , auc===0.633317 
Fold 1/4 , model 9 , auc===0.630786 
Fold 1/4 , model 10 , auc===0.634724 
Fold 1/4 , model 11 , auc===0.659364 
Fold 1/4 , model 12 , auc===0.626266 
Fold 1/4 , model 13 , auc===0.633244 
Fold 1/4 , model 14 , auc===0.641219 
Fold 1/4 , model 15 , auc===0.676776 
Fold 1/4 , model 16 , auc===0.636166 
Fold 1/4 , model 17 , auc===0.589593 
Fold 1/4 , model 18 , auc===0.661346 
=========== end of fold 1 in level 0 ===========
Fold 2/4 , model 0 , auc===0.655348 
Fold 2/4 , model 1 , auc===0.645461 
Fold 2/4 , model 2 , auc===0.667496 
Fold 2/4 , model 3 , auc===0.630246 
Fold 2/4 , model 7 , auc===0.630246 
Fold 2/4 , model 8 , auc===0.63013

In [0]:
0.658334
0.669428 13 feat
0.677179 19 feat
0.669545 0.668472 0.620526 19 feat

In [20]:
pred3=model.predict_proba(data[26775:])[:,1]

====================== Start of Level 0 ======================
1 estimators included in Level 0 
====================== Start of Level 1 ======================
1 estimators included in Level 1 


In [0]:
np.corrcoef(pred2,pred1)

array([[1.        , 0.53338678],
       [0.53338678, 1.        ]])

In [0]:
pred3=(pred1+pred2)/2

In [0]:
pred=model.predict(data[26775:])

In [0]:
result=pd.DataFrame({'UID':uid,'bad_flag':pred3})

In [0]:
result.to_csv('stacknet_19.csv',index=False)

In [0]:
from google.colab import files
files.download('stacknet_19.csv') 

In [25]:
pred3

array([0.03316236, 0.07143238, 0.02132068, ..., 0.09371744, 0.07672836,
       0.0362248 ])

In [0]:
pred2

array([0.01058083, 0.0191955 , 0.099851  , ..., 0.19468954, 0.19468954,
       0.07940339])

In [0]:
pred1

array([0.03566054, 0.03868789, 0.04571697, ..., 0.08832651, 0.05002373,
       0.03542971])

In [0]:
pred

array([0.02986203, 0.05458439, 0.04817231, ..., 0.11309585, 0.07494908,
       0.03440562])

In [0]:
def time(x,y):
  one=re.compile(r'\d{2}[-/]\d{2}[-/]\d{4}')
  two=recompile(r'\d{2}\w{3}\d{2})